apiVersion: 1
datasources:
  - name: Langfuse-ClickHouse
    type: grafana-clickhouse-datasource
    uid: langfuse-ch
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: clickhouse
      defaultDatabase: default
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
